### ISSUE TITLE
Slider Component

### ISSUE THREAD

**Issue by maazshakeel** [maazshakeel/devdynasty_project#20]
## Slider
- [x] Create Slider Component file in src/components/Slider.jsx
- [x] Write your code

**Comment by SharmaDhruv2511** [comment]
Hi  I want to work on this issue. Can you please assign it to me?

**Comment by SharmaDhruv2511** [comment]
one more help How can i setup the project locally?

**Comment by maazshakeel** [comment]
Actually Dhruv the slider component has already been implemented, you can work on something else if you want, feel free to go through issues or open one if you feel like.

How to setup?
Just clone the github repo and run npm i or yarn or whatever you prefer, and simply run : npm run dev or yarn dev.

**Comment by maazshakeel** [comment]
![image](https://github.com/maazshakeel/devdynasty_project/assets/62890173/f9baf48a-46b1-4ca0-aa98-225a213a818d)
